spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gskq_jjr
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    view:
      prefix: /admin/
      suffix: .jsp

server:
  port: 80
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml

    # mybatis-plus:
    # 1、MyBatis的全局配置文件
    # config-location: classpath:mybatis-config.xml
    # 2、MyBatis的映射配置文件 - *mapper.xml
    #mapper-locations: classpath*:mappers/*.xml
    # 3、实体别名扫描的包的路径
    #type-aliases-package: com.sunc.cwy.model


    # configuration:
    # 4、禁用自动的驼峰映射，默认true
    # map-underscore-to-camel-case: false
    # 5、全局的开启或禁用映射器的缓存，默认true
    # cache-enabled: false

    # global-config:
    # db-config:
    # 6、全局默认主键类型，设置后，即可省略实体对象中的@TableId(type = IdType.AUTO)配置
    # id-type: auto
    # 7、全局的表名前缀，配置后可省略@TableName()配置
    # table-prefix: mp_



